### ISSUE TITLE
ERROR [django.request:284] Internal Server Error: /createsession/

### ISSUE THREAD

**Issue by trongkyKMA** [kevthehermit/VolUtility#15]
ERROR [django.request:284] Internal Server Error: /createsession/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/forensics/VolUtility/web/views.py", line 228, in create_session
    logger.debug()
TypeError: debug() takes at least 2 arguments (1 given)

Help meeee. I submit file .vmem it failed 'like this. You can help me.thank you very much

**Comment by kevthehermit** [comment]
Can you git pull to get the new update and try again.

**Comment by trongkyKMA** [comment]
Thank you .I need to update what?python?mongodb? VolUlitily.

**Comment by kevthehermit** [comment]
@trongkyKMA 

cd in the volutility folder and run the command ```git pull``` This should update and fix your issue.

**Comment by trongkyKMA** [comment]
Thank you :)
