### ISSUE TITLE
imageinfo is not working

### ISSUE THREAD

**Issue by Beercow** [kevthehermit/VolUtility#29]
I was trying to fallow your GrrCON challenge and ran into some issues. The only version that I can get imageinfo to work on is v0.1-alpha. v0.2 produces the fallowing error:

DEBUG Running Plugin: imageinfo
DEBUG   : web.views           : Running Plugin: imageinfo
INFO    : volatility.debug    : Determining profile based on KDBG search...
Error Getting imageinfo: need more than 1 value to unpack
Error Getting imageinfo: need more than 1 value to unpack
Error Getting imageinfo: need more than 1 value to unpack
[15/Jun/2016 01:11:51] "POST /ajaxhandler/runplugin/ HTTP/1.1" 200 9
[15/Jun/2016 01:11:52] "POST /ajaxhandler/pollplugins/ HTTP/1.1" 200 96123

The latest v1.0-dev throws the fallowing error:

DEBUG Running Plugin: imageinfo
DEBUG   : web.views           : Running Plugin: imageinfo
INFO    : volatility.debug    : Determining profile based on KDBG search...
ERROR Internal Server Error: /ajaxhandler/runplugin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/remnux/Downloads/VolUtility-master/web/views.py", line 717, in ajax_handler
    plugin_name = run_plugin(request.POST['session_id'], request.POST['plugin_id'])
  File "/home/remnux/Downloads/VolUtility-master/web/views.py", line 552, in run_plugin
    for line in imageinfo_text.split('\n'):
AttributeError: 'int' object has no attribute 'split'
ERROR   : django.request      : Internal Server Error: /ajaxhandler/runplugin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/remnux/Downloads/VolUtility-master/web/views.py", line 717, in ajax_handler
    plugin_name = run_plugin(request.POST['session_id'], request.POST['plugin_id'])
  File "/home/remnux/Downloads/VolUtility-master/web/views.py", line 552, in run_plugin
    for line in imageinfo_text.split('\n'):
AttributeError: 'int' object has no attribute 'split'
[15/Jun/2016 01:21:17] "POST /ajaxhandler/runplugin/ HTTP/1.1" 500 17103
[15/Jun/2016 01:21:17] "POST /ajaxhandler/pollplugins/ HTTP/1.1" 200 95481

Not sure what has changed since v0.1-alpha that is causing these issues.

**Comment by kevthehermit** [comment]
Yeah sorry, When I updated the row ID mechanism forgot to update the imageinfo elements. 

Fixed with commit https://github.com/kevthehermit/VolUtility/commit/1e8a7e3edcb72a7f5fec910db53468886b27845a
