### ISSUE TITLE
VirustotalSearch returns 500 error

### ISSUE THREAD

**Issue by Lost4Now** [kevthehermit/VolUtility#48]
Doing virustotalsearch from ProcDump returns a 500.  

**Log output:**
ERROR Internal Server Error: /ajaxhandler/VirusTotalSearch/
Traceback (most recent call last):
  File "/home/steven/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/steven/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/steven/.local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/VolUtility/web/views.py", line 673, in ajax_handler
    extension.run()
  File "/opt/VolUtility/extensions/virustotalsearch/virustotalsearch.py", line 40, in run
    vt = PublicApi(self.config.api_key)
AttributeError: 'dict' object has no attribute 'api_key'

I fixed the problem by changing line 40 in the script from:
vt = PublicApi(self.config.api_key)

to:
vt = PublicApi(self.config['virustotal']['api_key'])

Sorry I don't have time or the mental capability tonight to do a pull request sorry.

**Comment by kevthehermit** [comment]
Thanks will fix in the morning
