### ISSUE TITLE
Error 500 issues on most plugins

### ISSUE THREAD

**Issue by volatilexaminer** [kevthehermit/VolUtility#64]
DEBUG   : web.views           : Running Plugin: pslist
ERROR Internal Server Error: /ajaxhandler/runplugin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sfllc/VolUtility/web/views.py", line 760, in ajax_handler
    plugin_name = run_plugin(request.POST['session_id'], request.POST['plugin_id'])
  File "/home/sfllc/VolUtility/web/views.py", line 356, in run_plugin
    plugin_options=plugin_options
  File "/home/sfllc/VolUtility/web/views.py", line 303, in try_run
    logger.debug("Testing: {0}".format(plugin_style))
NameError: global name 'plugin_style' is not defined
ERROR   : django.request      : Internal Server Error: /ajaxhandler/runplugin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sfllc/VolUtility/web/views.py", line 760, in ajax_handler
    plugin_name = run_plugin(request.POST['session_id'], request.POST['plugin_id'])
  File "/home/sfllc/VolUtility/web/views.py", line 356, in run_plugin
    plugin_options=plugin_options
  File "/home/sfllc/VolUtility/web/views.py", line 303, in try_run
    logger.debug("Testing: {0}".format(plugin_style))
NameError: global name 'plugin_style' is not defined
ERROR "POST /ajaxhandler/runplugin/ HTTP/1.1" 500 16815
ERROR   : django.server       : "POST /ajaxhandler/runplugin/ HTTP/1.1" 500 16815
INFO "POST /ajaxhandler/pollplugins/ HTTP/1.1" 200 71657
INFO    : django.server       : "POST /ajaxhandler/pollplugins/ HTTP/1.1" 200 71657

Everything seems to load fine when i run manage.py:
WARNING Using default config file. Check your volutility.conf file exists
INFO Loaded configuration from volutility.conf.sample
INFO Disabled Extension: cuckoosandbox
WARNING Using default config file. Check your volutility.conf file exists
INFO Loaded configuration from volutility.conf.sample
INFO Loaded Extension: ExifData
INFO Loaded Extension: ExtractStrings
INFO Loaded Extension: HexViewer
INFO Loaded Extension: HiveViewer
INFO Loaded Extension: IPLookup
INFO Loaded Extension: PSTViewer
INFO Loaded Extension: SqliteViewer
INFO Loaded Extension: VirusTotalSearch
INFO Loaded Extension: VolShell
INFO Loaded Extension: YaraScanner
WARNING Using default config file. Check your volutility.conf file exists
INFO Loaded configuration from volutility.conf.sample
WARNING Using default config file. Check your volutility.conf file exists
INFO Loaded configuration from volutility.conf.sample
System check identified no issues (0 silenced).
December 07, 2016 - 03:07:56
Django version 1.10.4, using settings 'volgui.settings'
Starting development server at http://0.0.0.0:8000/

Not sure if im doing something wrong or not.

**Comment by kevthehermit** [comment]
Thanks,

that was a silly mistake on my part. 

Testing now, will push new version up shortly
