### ISSUE TITLE
KeyError: 'extensions'

### ISSUE THREAD

**Issue by jasonblanks** [kevthehermit/VolUtility#65]
Hi looking forward to using this.  Came across trying to rule out any dependencies issues now, but installed following the ubuntu guide provided w/ local mongo 3.4.   

`sudo /opt/VolUtility/manage.py runserver 0.0.0.0:8080
Performing system checks...

WARNING Using default config file. Check your volutility.conf file exists
ERROR Unable to find a valid volutility.conf file.
INFO Loaded configuration from volutility.conf.sample
Unhandled exception in thread started by <function wrapper at 0x7f10d9136b90>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/VolUtility/volgui/urls.py", line 18, in <module>
    from web import views
  File "/opt/VolUtility/web/views.py", line 9, in <module>
    from web.modules import __extensions__
  File "/opt/VolUtility/web/modules.py", line 51, in <module>
    __extensions__ = load_extensions()
  File "/opt/VolUtility/web/modules.py", line 17, in load_extensions
    disable_list = config['extensions']['disabled'].split(',')
KeyError: 'extensions'
`

**Comment by kevthehermit** [comment]
Can you try copying volutility.conf.sample to volutility.conf and see if that changes anything.

**Comment by kevthehermit** [comment]
This issue seems to be a missing config fiel
ERROR Unable to find a valid volutility.conf file.

**Comment by jasonblanks** [comment]
DOH. Yes, this was it.   Sorry, Just assumed it defaulted to 'volutility.conf.sample' if not found.
